version: '3.9'

services:
  app:
    build: .
    container_name: app
    ports:
      - ${API_PORT:-3333}:3333
    depends_on:
      - database
    environment:
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
    volumes:
      - app_data:/usr/src/app/data
    networks:
      - net
    restart: always

  database:
    image: bitnami/postgresql
    container_name: database
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/postgresql
    networks:
      - net
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 2s
      retries: 20

networks:
  net:
    driver: bridge

volumes:
  app_data:
  db_data:
